### ISSUE TITLE
[meta] Improve documentation

### ISSUE THREAD

**Issue by brynpickering** [calliope-project/calliope#358]
This meta issue is linked to a number of sub-issues that need to be solved to improve users' understanding of how to build, run, and analyse a Calliope model. This includes more examples of its use as well as better descriptions of inputs and outputs.

- [x] Examples of technology definitions (#94)
- [ ] Better document example models (#325)   
- [x] Document automatic internal magic (distance derivations, depreciation cost calculations, LCOE and capacity factor postprocessing results) (#209)
- [ ] Tutorials for advanced functionality (#95) 
- [x] Add spell checking (#88) 
- [ ] Limits of operational mode (#350)

**Comment by brynpickering** [comment]
Main aim of documentation should be to showcase how we provide the basic building blocks to define an energy system model (`nodes`; `techs` inc. `supply`, `conversion`, ...; `links`) and how one can easily put those blocks together into a model. Doing more (`custom constraints`, `plotting`, `timeseries aggregation`, ...) is then another section about how users can take their modelling further when they understand the building blocks.

**Comment by brynpickering** [comment]
Closing as a stale meta issue. Opening a new issue to focus on better documenting `operate` mode (a new notebook tutorial)
